id: P000405
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:38:16.017813
source_metadata:
  id: bdr:W00KG02331
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༩
  author: ''
  volumes: {}
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
